version: '3'

services:
    app:
        build: 
            context: ./
            dockerfile: Dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-php

    nginx:
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-php

networks:
    app-php:
        driver: bridge
